# Kernel SVM

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
!pip install colabcode

     |████████████████████████████████| 45 kB 1.7 MB/s 
     |████████████████████████████████| 745 kB 9.2 MB/s 
     |████████████████████████████████| 8.3 MB 23.9 MB/s 
     |████████████████████████████████| 58 kB 5.1 MB/s 
     |████████████████████████████████| 393 kB 69.4 MB/s 
     |████████████████████████████████| 428 kB 68.0 MB/s 
     |████████████████████████████████| 54 kB 3.0 MB/s 
     |████████████████████████████████| 125 kB 59.3 MB/s 
     |████████████████████████████████| 78 kB 6.2 MB/s 
     |████████████████████████████████| 52 kB 1.5 MB/s 
     |████████████████████████████████| 124 kB 58.8 MB/s 
     |████████████████████████████████| 124 kB 39.9 MB/s 
     |████████████████████████████████| 122 kB 50.3 MB/s 
     |████████████████████████████████| 122 kB 60.0 MB/s 
     |████████████████████████████████| 122 kB 50.7 MB/s 
     |████████████████████████████████| 122 kB 58.5 MB/s 
     |████████████████████████████████| 112 kB 49.9 MB/s 
     |███████████████████

In [1]:
!pip install fastapi

     |████████████████████████████████| 51 kB 466 kB/s 
     |████████████████████████████████| 61 kB 252 kB/s 
     |████████████████████████████████| 10.1 MB 14.4 MB/s 


## Importing the dataset

In [ ]:
dataset = pd.read_csv('cardio_train_new_upload_1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Kernel SVM model on the Training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Predicting a new result

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [1 0]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[6760 2060]
 [2699 5981]]


0.7280571428571428

In [2]:
from colabcode import ColabCode

In [3]:
from fastapi import FastAPI

In [4]:
cc=ColabCode(port=12000,code=False)

In [6]:
app=FastAPI()
@app.get("/")
async def read_root():
  return {"Hello":"World"}


In [7]:
cc.run_app(app=app)

INFO:     Started server process [158]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:12000 (Press CTRL+C to quit)


Public URL: NgrokTunnel: "https://9585-35-243-153-207.ngrok.io" -> "http://localhost:12000"
INFO:     2409:4071:2496:44db:10e6:7ea1:841a:a510:0 - "GET / HTTP/1.1" 200 OK
INFO:     2409:4071:2496:44db:10e6:7ea1:841a:a510:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found


INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [158]


In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle
dataset = pd.read_csv('cardio_train_new_upload_1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [1 0]]
[[6760 2060]
 [2699 5981]]


0.7280571428571428

In [11]:
data.to_pickle("my_data.pkl")

NameError: ignored

In [12]:
dataset.to_pickle("my_data.pkl")

In [13]:
pickle.dump(model_f, open("model_gb.pkl", "wb"))

NameError: ignored

In [15]:
a=classifier.fit(X_train, y_train)

In [16]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [1 0]]
[[6760 2060]
 [2699 5981]]


0.7280571428571428

In [17]:
pickle.dump(a, open("model_gb.pkl", "wb"))

In [19]:
%%writefile models.py
from pydantic import BaseModel, conlist
from typing import List


class Heart(BaseModel):
    data: List[conlist(int, min_items=11, max_items=11)]

Writing models.py


In [20]:
import pickle
import logging
from fastapi import FastAPI

In [21]:
app = FastAPI(title="ML Models as API on Google Colab", description="with FastAPI and ColabCode", version="1.0")


In [ ]:
model = None

@app.on_event("startup")
def load_model():
    global model
    model = pickle.load(open("model_gb.pkl", "rb"))

@app.post("/api", tags=["prediction"])
async def get_predictions(dataset:Heart)
    try:
        dataset = dict(iris)['data']
        print(data)
        iris_types = {
            0: 'setosa',
            1: 'versicolor',
            2: 'virginica'
        }
        prediction = list(map(lambda x: iris_types[x], model.predict(data).tolist()))
        log_proba = model.predict_log_proba(data).tolist()
        return {"prediction": prediction, "log_proba": log_proba}
    except:
        my_logger.error("Something went wrong!")
        return {"prediction": "error"}